---
title: "Syllabus"
description: |
  What does this course involve?
output:
  distill::distill_article:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Course objectives

The overarching goal of this course is to promote a critical attitude towards analytical inquiry in Economics and Business. It introduces students industry standard tools and fundamental ideas so they can engage with different kinds of data in appropriately rigorous ways.

Other objectives of the course include:

* Developing students' analytical, quantitative reasoning, and communication skills

* Encourage critical thinking about data and analytical methods

* Prepare students for future careers in data business and economics

* To prepare students to engage upper level economics and business courses

Broadly, the course is organized into three sections. 

1. **Review of Probability and Statistics** The course will begin where Introduction to Statistics (MA005 or equivalent) ended. The review covers descriptive statistics, probability theory, and inferential statistics in one and two variables. It servers also as a platform for learning R, which is a language and environment for statistical computing and graphics.

2. **Linear Regression** The main statistical technique in this course is Ordinary Least Squares (OLS), which is a common tool for modeling economic systems and generating forecasts.  In addition to building, interpreting, evaluating OLS regressions, this part of the course explores situations where OLS regression is inappropriate or otherwise inadequate. 

3. **Calculus** The final part of the course will introduce calculus. This section facilitates future classes in the Economics & Business major.

By the end of this course, students will also be able to perform basic data wrangling and visualization tasks. students will also be able to build and interpret OLS regressions using R. Students will appreciate the common failures of the linear model and be able to detect and correct for them. Students will able to use linear regression models to generate forecasts. 

# Prerequisites

Students must have taken MA005, Introduction to Statistics or equivalent in its entirety.

# Resources

1. **This site** Lecture materials and problem sets will be posted to this site.  There will be a link to this page on the [Westmont Canvas site](http://canvas.westmont.edu/) and another link on my [homepage](https://emanlapig.net). 

1. **Textbooks** This class will rely upon two texts. 

    * The introduction to R will come from the (free) text [R4DS](https://r4ds.had.co.nz/)
    * The material covering will be from Econometrics 6th ed. by A.H. Studenmund and published by Addison-Wesley, which is available at the bookstore
    * The calculus material will not rely upon a textbook but many excellent texts exist - please [contact the  instructor](mailto://emanlapig@westmont) for recommendations

1. **Lectures** The main ideas, techniques, and worked examples will be presented during lectures in a workshop style. Students will need a laptop in each class meeting

1. **Office hours** Please feel free to [make an appointment](https://calendar.x.ai/enricomanlapig)







# Assessment

## Examinations

Students will sit three exams (two midterms plus a final) corresponding to the three sections in the course. Examinations are not intended to be cumulative but because the course builds on itself, repetition is unavoidable. Dates, times, locations, and format will be advised although general timing is indicated in the tentative topic schedule below. Examinations are weighted as follows:

1. Probability & Statistics Review: 25%

2. Linear regression: 25%

3. Calculus: 10% (Pass or fail)

*Total grade value: 60%*


## Problem sets

To encourage continuous engagement with the material, students will complete weekly problem sets. Students are encouraged to work on these in groups but you must submit individual work. Submissions should be to Canvas. 




*Total grade value: 25%*


## Visualization  

To encourage continuous engagement with material, students will submit weekly visualizations using the weekly [Tidy Tuesday dataset](https://github.com/rfordatascience/tidytuesday). Please post your visualizations to the E&B #Tidy-Tuesday Slack channel

*Total grade value: 10%*


## Participation

Students are expected to engage in class by asking/responding to questions. Participation credit (beyond attendance) is awarded at the end of the semester.

*Total grade value: 5%*


# Tentative schedule

The schedule below indicates the approximate timing of each topic.  


#### Week 1: Working with R

* Base R
* Typesetting in R
    
#### Week 2: Introduction to descriptive descriptive statistics

* Packages for data manipulation and visualization
* Introduction to web scraping
    
#### Week 3: Reviewing probability theory

* Key theorems in probability theory
* Monte-carlo simulation
* Quantitative finance
    
#### Week 4: Reviewing inferential statistics

* Introduces estimators and their properties
    
#### Week 5: Mid-semester Examination 1

#### Week 6: OLS and the Gauss Markov Theorem
* Simple and multiple regression
* Variance decomposition
* OLS
    
#### Week 7: Inference
* Hypothesis testing
* Forecasting
    
#### Week 8: Modeling skills
* Dummy variables
* Log forms
* Interaction



#### Week 9: When Gauss Markov fails Part 1
* Model misspecification
* Multi-collinearity



#### Week 10: Spring Break


#### Week 11: When Gauss Markov fails Part 2
* Heteroskedasticity
* Serial-correlation

#### Weeks 12 and 13: Selected topics
* Topics may include categorical data, time series, endogeneity, or other topics depending upon the interest of the students and instructor

#### Week 14: Mid-semester Examination 2

#### Week 15 to end: Calculus







# Policies

### Attendance

Your regular attendance and active participation in class is very important and expected. Following college Significant unexcused absences (3 or more classes) or lack of participation (missed assignments) or some combination may result in penalties or dismissal from the course in accordance with the college's [attendance policies](https://www.westmont.edu/office-registrar/academic-policies-and-procedures/attendance-policies) as documented below. 

Any absence from a scheduled examination or other assessment must be accompanied by appropriate documentation.

### Academic integrity 

Dishonesty of any kind may result in loss of credit for the work involved and the filing of a report with the Provost’s Office. Major or repeated infractions may result in dismissal from the course with a grade of F. Be familiar with [Westmont’s plagiarism policy](http://www.westmont.edu/_offices/provost/Plagiarism/academic_integrity_policy.html).

Within the context of this class, you are encouraged to work in groups with your classmates. You are welcome to share code, share ideas, and help each other with problem sets and class exercises. You are also welcome to use the internet to find examples, clarify syntax, or clarify concepts. However, you are not to engage with live sources beyond the people in the class for specific help with assignments. For example, utilizing social media for homework help, posting questions to online boards, or participating in online chat forums/boards for help with problem sets or other assignments is considered cheating. Similarly, utilizing outside resources that provide specific solutions (e.g. Chegg, solutions manuals, or the submissions of past students) is also considered cheating.  

### Academic accommodations

Students who have been diagnosed with a disability are strongly encouraged to contact the Office of Disability Services as early as possible to discuss appropriate accommodations for this course. Formal accommodations will only be granted for students whose disabilities have been verified by the Office of Disability Services. These accommodations may be necessary to ensure your equal access to this course. Please contact Sheri Noble, Director of Disability Services. (310A Voskuyl Library, (805) 565-6186, snoble@westmont.edu) or visit the [website]([http://www.westmont.edu/_offices/disability/].) for more information.

